database:
  user: <USERNAME> # default to postgres
  password: <PASSWORD> # default to ""
  db: <DATABASENAME> # default to test
  host: <HOSTNAME> # default to localhost
  port: <PORTNAME> # default to 5432
notification:
  - slack:
      token: <API-TOKEN>
      channel: <SLACK-CHANNEL>
  - email:
      sender: <EMAIL-ADDRESS>
      sender_password: <EMAIL-PASSWORD>
      receiver: <EMAIL-ADDRESS>
